# Generated by Django 5.0.3 on 2024-03-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploaded_images/')),
                ('upscale_image', models.ImageField(blank=True, default='default_upscale_image.jpg', upload_to='upscaled_images/')),
                ('upscaled_image_data', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
